### ISSUE TITLE
Can't call method "answer" on an undefined value

### ISSUE THREAD

**Issue by MarrsAttax** [Perl-Email-Project/Email-Valid#22]
Occasionally the code crashes with error: Can't call method "answer" on an undefined value at /usr/local/lib64/perl5/5.20.2/Email/Valid.pm line 153.

The code needs to check if $resolver->search returns undef (as it would if no answers were found) before it attempts to call the "answer" method and handle this gracefully.

**Comment by boysenberrypayne** [comment]
This has been effecting our production server as well.  Is there an eta on getting this pushed out?
I am thinking one answer is to remove the Net::DNS::Resolver dependancy and use the nslookup fallback until this is fixed.

**Comment by rjbs** [comment]
I believe this is fixed in today's release.
