### ISSUE TITLE
.invalid tlds should not be valid email addresses?

### ISSUE THREAD

**Issue by singingfish** [Perl-Email-Project/Email-Valid#24]
According to [wikipedia](https://en.wikipedia.org/wiki/.invalid), the .invalid tld is always invalid.  Here's a failing test case that shows email::valid considers example.invalid a valid email domain.

[invalid_tld.diff.txt](https://github.com/Perl-Email-Project/Email-Valid/files/123885/invalid_tld.diff.txt)

**Comment by rjbs** [comment]
this has been updated in today's release
