### ISSUE TITLE
one invalid email address

### ISSUE THREAD

**Issue by emanean** [Perl-Email-Project/Email-Valid#28]
the email address: rw!llams@funnyguys.info comes through as valid and it should not.

**Comment by rjbs** [comment]
Why do you think it should not?

**Comment by emanean** [comment]
I do not believe the "!" is allowed in the name.

**Comment by rjbs** [comment]
I believe you are mistaken.  Neither RFC 821 nor RFC 822 mention the exclamation point in any way whatsoever.  RFC 5321 also does not.  RFC 5322 mentions ! only to *include* it in `atext`, making it *expressly allowed*.

Please re-open this if you have evidence that I am mistaken.  I feel pretty confident this time, though.
