### ISSUE TITLE
Nasty hacks -- Latest TLD stuff broken -- causes death

### ISSUE THREAD

**Issue by ddblack** [Perl-Email-Project/Email-Valid#39]
IMHO, This module is really hacked these days.

I say get rid of the hacks.  This module has worked as expected for YEARS.  

Use Net:DNS with a timeout/threaded timeout and look for an SOA record on the email addrs [domainpart].  

Again, this module is really nasty, now.  "nslookup" integration?  LOL.

This module used to be clean and simple.  TLD checks are ridiculous.  Just focus on an SOA, MX, and valid A record.  (If the remote end doesn't comply with that simple rule, then they don't deserve to be on the internet, anyway.)

If someone wants all the fluff, then subclass it and call it Email::Valid::Fluff.

My two cents.

In the meantime, I'm going back to a version that worked 4 years ago until I can rewrite this thing the way it oughta be.

**Comment by rjbs** [comment]
You can turn off all the features you don't like.
